/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.ui;

import fr.unice.polytech.polybot.botdsl.ui.AbstractBotDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BotDslUiModule extends AbstractBotDslUiModule {
  public BotDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
