/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl;

import fr.unice.polytech.polybot.botdsl.BotDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotDslStandaloneSetup extends BotDslStandaloneSetupGenerated {
  public static void doSetup() {
    new BotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
