/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl;

import fr.unice.polytech.polybot.botdsl.AbstractBotDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotDslRuntimeModule extends AbstractBotDslRuntimeModule {
}
