/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.polybot.botdsl.parser.antlr.internal.InternalBotDslParser;
import fr.unice.polytech.polybot.botdsl.services.BotDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BotDslParser extends AbstractAntlrParser {

	@Inject
	private BotDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBotDslParser createParser(XtextTokenStream stream) {
		return new InternalBotDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Scene";
	}

	public BotDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BotDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
