/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBotDslScopeProvider extends DelegatingScopeProvider {
}
