/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.ui;

import com.google.inject.Injector;
import fr.unice.polytech.polybot.mydsl.ui.internal.MydslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BotDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MydslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MydslActivator activator = MydslActivator.getInstance();
		return activator != null ? activator.getInjector(MydslActivator.FR_UNICE_POLYTECH_POLYBOT_BOTDSL_BOTDSL) : null;
	}

}
