/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.polybot.botdsl.BotDslRuntimeModule;
import fr.unice.polytech.polybot.botdsl.BotDslStandaloneSetup;
import fr.unice.polytech.polybot.botdsl.ide.BotDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BotDslIdeSetup extends BotDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    BotDslRuntimeModule _botDslRuntimeModule = new BotDslRuntimeModule();
    BotDslIdeModule _botDslIdeModule = new BotDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_botDslRuntimeModule, _botDslIdeModule));
  }
}
