/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.polybot.botdsl.ide;

import fr.unice.polytech.polybot.botdsl.ide.AbstractBotDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BotDslIdeModule extends AbstractBotDslIdeModule {
}
